### ISSUE TITLE
INTERFAZ DE BUSCAR_EDITAR_ELIMINAR USUARIO

### ISSUE THREAD

**Issue by AdisOrtiz** [CarsOk/castillo_del_rey#89]

**Comment by OscarEsc10** [comment]
https://www.canva.com/design/DAFJVl4GikU/34qljRxWAFG_EOBku9aMxA/edit?utm_content=DAFJVl4GikU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by OscarEsc10** [comment]
![Copia de buscar](https://user-images.githubusercontent.com/99421143/185040383-f7a190a3-ce41-4a4a-b3cd-260d99582719.png)

**Comment by OscarEsc10** [comment]
![Copia de Agregar un título](https://user-images.githubusercontent.com/99421143/185041847-2fefe395-0851-4e41-b6f1-4a7eee37cfca.png)
